version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: rewind
    ports:
      - "5432:5432"

  cache:
    image: redis
    restart: always
    ports:
      - "6378:6379"
    command:
      - "--save ''"
      - "--notify-keyspace-events 'AKE'"
